// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt4oiNMMB-3fwmJ8cQcBVQNDky4HrokU8',
    appId: '1:531763124274:web:0286ab5453e14c738c442b',
    messagingSenderId: '531763124274',
    projectId: 'muict424prj-traveldiary',
    authDomain: 'muict424prj-traveldiary.firebaseapp.com',
    storageBucket: 'muict424prj-traveldiary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdXP1YPUxZeQ6JwFErRiTDvW5KHOpJSIQ',
    appId: '1:531763124274:android:293cd36e647288828c442b',
    messagingSenderId: '531763124274',
    projectId: 'muict424prj-traveldiary',
    storageBucket: 'muict424prj-traveldiary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NlMRMzoRF1UE0vTH34U-gcCRkfjvMaY',
    appId: '1:531763124274:ios:c59a6ef97f97f2768c442b',
    messagingSenderId: '531763124274',
    projectId: 'muict424prj-traveldiary',
    storageBucket: 'muict424prj-traveldiary.appspot.com',
    iosBundleId: 'com.example.travelDiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NlMRMzoRF1UE0vTH34U-gcCRkfjvMaY',
    appId: '1:531763124274:ios:cf249d44f0b9f78a8c442b',
    messagingSenderId: '531763124274',
    projectId: 'muict424prj-traveldiary',
    storageBucket: 'muict424prj-traveldiary.appspot.com',
    iosBundleId: 'com.example.travelDiaryApp.RunnerTests',
  );
}
