name: travel_diary_app
description: "A Flutter app to help users to keep track and memmories of their travel places, By GoodBoys team."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  table_calendar: ^3.0.9
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_core_platform_interface: ^5.0.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.10
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/logo.png
    - assets/Location_marker.png
